var myApp = angular.module("myApp", ["ngRoute", "ngResource", "myApp.services"]);

var services = angular.module("myApp.services", ["ngResource"]);
services.factory('Wine', function($resource) {
    return $resource('http://localhost:5000/findmywine/api/v1/wines/:id', {id: '@id'}, {
        get: { method: 'GET' },
        delete: { method: 'DELETE' }
    });
});

services.factory('Search', function($resource) {
    return $resource('http://localhost:5000/findmywine/api/v1/search', {q: '@q'}, {
        query: { method: 'GET', isArray: true}
    });
});

myApp.config(function($routeProvider) {
    $routeProvider
    .when('/', {
        templateUrl: 'templates/main.html',
        controller: 'usercontroller'
    })
    .when('/wines/:id',{
        templateUrl: 'templates/wine_details.html',
        controller: 'wineDetailsController'
    })
});


//https://stackoverflow.com/questions/14514461/how-do-i-bind-to-list-of-checkbox-values-with-angularjs
//http://jsbin.com/dowohesunu/edit?html,js,output
myApp.controller('mainController', function($scope, Search){
  $scope.fruits = ['cherry','berry','plum','apple','blackberry','citrus','vanilla','pepper',
  'peach','raspberry','chocolate','currant','lemon','pear','orange','licorice','lime','tart',
  'grapefruit','coffee','melon','strawberry','honey','pineapple','apricot','jam','almond',
  'cranberry','herbs','blueberry','cinnamon','mocha','mint','grape','tea','cherries','pie',
  'prune','sage','raisin','tomato','mango','nectarine','sour','berries','coconut','pomegranate',
  'butter','olive','bacon','mushroom','fig','thyme','butterscotch','mousse','ginger','lychee',
  'bread','rhubarb','jasmine','liqueur','truffle','yeast','nut','balsamic','hazelnut','quince',
  'fennel','watermelon','dill','beer','custard','guava','marmalade','pork','cardamom']

  $scope.selection = []
  $scope.toggleSelection = function toggleSelection(fruitName) {
    var idx = $scope.selection.indexOf(fruitName);

    // Is currently selected
    if (idx > -1) {
      $scope.selection.splice(idx, 1);
    }

    // Is newly selected
    else {
      $scope.selection.push(fruitName);
    }

    q = $scope.selection.toString()
    $scope.results = Search.query({q:q});
  };
});

myApp.controller(
    'wineDetailsController', ['$scope', 'Wine', '$routeParams',
    function ($scope, Wine, $routeParams) {
        $scope.wine = Wine.get({id: $routeParams.id});
    }
]);

myApp.controller("usercontroller", function($scope, Search){
      $scope.countryList = [
           'cherry cherry',
'cherry berry',
'cherry plum',
'cherry pepper',
'cherry licorice',
'cherry raspberry',
'cherry vanilla',
'cherry coffee',
'cherry blackberry',
'cherry chocolate',
'berry cherry',
'berry berry',
'berry plum',
'berry pepper',
'berry licorice',
'berry raspberry',
'berry vanilla',
'berry coffee',
'berry chocolate',
'berry blackberry',
'plum cherry',
'plum berry',
'plum plum',
'plum pepper',
'plum vanilla',
'plum raspberry',
'plum licorice',
'plum coffee',
'plum blackberry',
'plum chocolate',
'apple cherry',
'apple berry',
'apple plum',
'apple apple',
'apple pepper',
'apple vanilla',
'apple raspberry',
'apple licorice',
'apple coffee',
'apple blackberry',
'blackberry cherry',
'blackberry berry',
'blackberry plum',
'blackberry apple',
'blackberry blackberry',
'blackberry pepper',
'blackberry vanilla',
'blackberry raspberry',
'blackberry licorice',
'blackberry chocolate',
'citrus cherry',
'citrus berry',
'citrus plum',
'citrus apple',
'citrus blackberry',
'citrus citrus',
'citrus pepper',
'citrus vanilla',
'citrus raspberry',
'citrus licorice',
'vanilla cherry',
'vanilla berry',
'vanilla plum',
'vanilla vanilla',
'vanilla apple',
'vanilla blackberry',
'vanilla citrus',
'vanilla pepper',
'vanilla raspberry',
'vanilla chocolate',
'pepper cherry',
'pepper berry',
'pepper plum',
'pepper pepper',
'pepper vanilla',
'pepper apple',
'pepper blackberry',
'pepper citrus',
'pepper raspberry',
'pepper chocolate',
'peach cherry',
'peach berry',
'peach plum',
'peach pepper',
'peach vanilla',
'peach apple',
'peach blackberry',
'peach citrus',
'peach peach',
'peach raspberry',
'raspberry cherry',
'raspberry berry',
'raspberry plum',
'raspberry pepper',
'raspberry vanilla',
'raspberry apple',
'raspberry blackberry',
'raspberry citrus',
'raspberry peach',
'raspberry raspberry',
'chocolate cherry',
'chocolate berry',
'chocolate plum',
'chocolate pepper',
'chocolate vanilla',
'chocolate apple',
'chocolate blackberry',
'chocolate citrus',
'chocolate raspberry',
'chocolate peach',
'currant cherry',
'currant berry',
'currant plum',
'currant pepper',
'currant vanilla',
'currant apple',
'currant blackberry',
'currant citrus',
'currant raspberry',
'currant chocolate',
'lemon cherry',
'lemon berry',
'lemon plum',
'lemon pepper',
'lemon apple',
'lemon vanilla',
'lemon blackberry',
'lemon citrus',
'lemon peach',
'lemon raspberry',
'pear cherry',
'pear berry',
'pear plum',
'pear apple',
'pear pepper',
'pear vanilla',
'pear blackberry',
'pear citrus',
'pear peach',
'pear raspberry',
'orange cherry',
'orange berry',
'orange plum',
'orange apple',
'orange pepper',
'orange vanilla',
'orange blackberry',
'orange citrus',
'orange peach',
'orange pear',
'licorice cherry',
'licorice berry',
'licorice plum',
'licorice pepper',
'licorice apple',
'licorice vanilla',
'licorice blackberry',
'licorice citrus',
'licorice peach',
'licorice raspberry',
'lime cherry',
'lime berry',
'lime plum',
'lime apple',
'lime pepper',
'lime vanilla',
'lime citrus',
'lime blackberry',
'lime peach',
'lime pear',
'tart cherry',
'tart berry',
'tart plum',
'tart apple',
'tart pepper',
'tart vanilla',
'tart citrus',
'tart blackberry',
'tart peach',
'tart pear',
'grapefruit cherry',
'grapefruit berry',
'grapefruit plum',
'grapefruit apple',
'grapefruit pepper',
'grapefruit vanilla',
'grapefruit citrus',
'grapefruit blackberry',
'grapefruit lemon',
'grapefruit peach',
'coffee cherry',
'coffee berry',
'coffee plum',
'coffee apple',
'coffee pepper',
'coffee vanilla',
'coffee citrus',
'coffee blackberry',
'coffee lemon',
'coffee peach',
'melon cherry',
'melon berry',
'melon plum',
'melon apple',
'melon pepper',
'melon vanilla',
'melon citrus',
'melon peach',
'melon blackberry',
'melon lemon',
'strawberry cherry',
'strawberry berry',
'strawberry plum',
'strawberry apple',
'strawberry pepper',
'strawberry vanilla',
'strawberry citrus',
'strawberry blackberry',
'strawberry peach',
'strawberry lemon',
'honey cherry',
'honey berry',
'honey plum',
'honey apple',
'honey pepper',
'honey vanilla',
'honey citrus',
'honey peach',
'honey lemon',
'honey blackberry',
'pineapple cherry',
'pineapple berry',
'pineapple plum',
'pineapple apple',
'pineapple pepper',
'pineapple vanilla',
'pineapple citrus',
'pineapple peach',
'pineapple lemon',
'pineapple blackberry',
'apricot cherry',
'apricot berry',
'apricot plum',
'apricot apple',
'apricot pepper',
'apricot vanilla',
'apricot citrus',
'apricot peach',
'apricot lemon',
'apricot pear',
'jam cherry',
'jam berry',
'jam plum',
'jam apple',
'jam pepper',
'jam vanilla',
'jam citrus',
'jam peach',
'jam lemon',
'jam blackberry',
'cranberry cherry',
'cranberry berry',
'cranberry plum',
'cranberry apple',
'cranberry pepper',
'cranberry vanilla',
'cranberry citrus',
'cranberry peach',
'cranberry lemon',
'cranberry blackberry',
'blueberry cherry',
'blueberry berry',
'blueberry plum',
'blueberry apple',
'blueberry vanilla',
'blueberry pepper',
'blueberry citrus',
'blueberry peach',
'blueberry lemon',
'blueberry blackberry',
'cinnamon cherry',
'cinnamon berry',
'cinnamon plum',
'cinnamon apple',
'cinnamon pepper',
'cinnamon vanilla',
'cinnamon citrus',
'cinnamon peach',
'cinnamon lemon',
'cinnamon blackberry',
'mocha cherry',
'mocha berry',
'mocha plum',
'mocha apple',
'mocha pepper',
'mocha vanilla',
'mocha citrus',
'mocha peach',
'mocha lemon',
'mocha blackberry',
'mint cherry',
'mint berry',
'mint plum',
'mint apple',
'mint pepper',
'mint vanilla',
'mint citrus',
'mint peach',
'mint lemon',
'mint blackberry',
'tea cherry',
'tea berry',
'tea plum',
'tea apple',
'tea pepper',
'tea vanilla',
'tea citrus',
'tea peach',
'tea blackberry',
'tea lemon',
'pie cherry',
'pie berry',
'pie plum',
'pie apple',
'pie pepper',
'pie vanilla',
'pie citrus',
'pie peach',
'pie blackberry',
'pie lemon',
'prune cherry',
'prune berry',
'prune plum',
'prune apple',
'prune pepper',
'prune vanilla',
'prune citrus',
'prune peach',
'prune blackberry',
'prune lemon',
'raisin cherry',
'raisin berry',
'raisin plum',
'raisin apple',
'raisin pepper',
'raisin vanilla',
'raisin citrus',
'raisin peach',
'raisin blackberry',
'raisin lemon',
'tomato cherry',
'tomato berry',
'tomato plum',
'tomato apple',
'tomato pepper',
'tomato vanilla',
'tomato citrus',
'tomato peach',
'tomato blackberry',
'tomato lemon',
'mango cherry',
'mango berry',
'mango plum',
'mango apple',
'mango pepper',
'mango vanilla',
'mango citrus',
'mango peach',
'mango blackberry',
'mango lemon',
'nectarine cherry',
'nectarine berry',
'nectarine plum',
'nectarine apple',
'nectarine pepper',
'nectarine vanilla',
'nectarine citrus',
'nectarine peach',
'nectarine blackberry',
'nectarine lemon',
'coconut cherry',
'coconut berry',
'coconut plum',
'coconut apple',
'coconut pepper',
'coconut vanilla',
'coconut citrus',
'coconut peach',
'coconut blackberry',
'coconut lemon',
'pomegranate cherry',
'pomegranate berry',
'pomegranate plum',
'pomegranate apple',
'pomegranate pepper',
'pomegranate vanilla',
'pomegranate citrus',
'pomegranate peach',
'pomegranate blackberry',
'pomegranate lemon',
'fig cherry',
'fig berry',
'fig plum',
'fig apple',
'fig pepper',
'fig vanilla',
'fig citrus',
'fig peach',
'fig blackberry',
'fig lemon',
'thyme cherry',
'thyme berry',
'thyme plum',
'thyme apple',
'thyme pepper',
'thyme vanilla',
'thyme citrus',
'thyme peach',
'thyme blackberry',
'thyme lemon',
'butterscotch cherry',
'butterscotch berry',
'butterscotch plum',
'butterscotch apple',
'butterscotch pepper',
'butterscotch vanilla',
'butterscotch citrus',
'butterscotch peach',
'butterscotch blackberry',
'butterscotch lemon',
'mousse cherry',
'mousse berry',
'mousse plum',
'mousse apple',
'mousse pepper',
'mousse vanilla',
'mousse citrus',
'mousse peach',
'mousse blackberry',
'mousse lemon',
'ginger cherry',
'ginger berry',
'ginger plum',
'ginger apple',
'ginger pepper',
'ginger vanilla',
'ginger citrus',
'ginger peach',
'ginger blackberry',
'ginger lemon',
'rhubarb cherry',
'rhubarb berry',
'rhubarb plum',
'rhubarb apple',
'rhubarb pepper',
'rhubarb vanilla',
'rhubarb citrus',
'rhubarb peach',
'rhubarb blackberry',
'rhubarb lemon',
'jasmine cherry',
'jasmine berry',
'jasmine plum',
'jasmine apple',
'jasmine pepper',
'jasmine vanilla',
'jasmine citrus',
'jasmine peach',
'jasmine blackberry',
'jasmine lemon',
'liqueur cherry',
'liqueur berry',
'liqueur plum',
'liqueur apple',
'liqueur pepper',
'liqueur vanilla',
'liqueur citrus',
'liqueur peach',
'liqueur blackberry',
'liqueur lemon',
'truffle cherry',
'truffle berry',
'truffle plum',
'truffle apple',
'truffle pepper',
'truffle vanilla',
'truffle citrus',
'truffle peach',
'truffle blackberry',
'truffle lemon',
'nut cherry',
'nut berry',
'nut plum',
'nut apple',
'nut pepper',
'nut vanilla',
'nut citrus',
'nut peach',
'nut lemon',
'nut blackberry',
'balsamic cherry',
'balsamic berry',
'balsamic plum',
'balsamic apple',
'balsamic pepper',
'balsamic vanilla',
'balsamic citrus',
'balsamic peach',
'balsamic lemon',
'balsamic blackberry',
'hazelnut cherry',
'hazelnut berry',
'hazelnut plum',
'hazelnut apple',
'hazelnut pepper',
'hazelnut vanilla',
'hazelnut citrus',
'hazelnut peach',
'hazelnut lemon',
'hazelnut blackberry',
'watermelon cherry',
'watermelon berry',
'watermelon plum',
'watermelon apple',
'watermelon pepper',
'watermelon vanilla',
'watermelon citrus',
'watermelon peach',
'watermelon lemon',
'watermelon blackberry',
'dill cherry',
'dill berry',
'dill plum',
'dill apple',
'dill pepper',
'dill vanilla',
'dill citrus',
'dill peach',
'dill blackberry',
'dill lemon',
'custard cherry',
'custard berry',
'custard plum',
'custard apple',
'custard pepper',
'custard vanilla',
'custard citrus',
'custard peach',
'custard blackberry',
'custard lemon',
'marmalade cherry',
'marmalade berry',
'marmalade plum',
'marmalade apple',
'marmalade pepper',
'marmalade vanilla',
'marmalade citrus',
'marmalade peach',
'marmalade blackberry',
'marmalade lemon'
      ];
      $scope.complete = function(string){
           $scope.hidethis = false;
           var output = [];
           angular.forEach($scope.countryList, function(country){
                if(country.toLowerCase().indexOf(string.toLowerCase()) >= 0)
                {
                     output.push(country);
                }
           });
           $scope.filterCountry = output;
      }
      $scope.fillTextbox = function(string){
           $scope.country = string;
           $scope.hidethis = true;

           q = string;
           console.log(Search.query({q:q}))
           $scope.results = Search.query({q:q});
      }

 });
